### ISSUE TITLE
Editing and adding new lines

### ISSUE THREAD

**Issue by oceatoon** [camohub/jquery-sortable-lists#1]
Hi 
We're planning on using your lib that we just discovered 
it looks really cool 
we plan on doing edit lines content and being able to add/remove new lines 
it's fairly simple , I know, but maybe it's something you have allready done ? 
Cheers

**Comment by camohub** [comment]
I didn´t implemet Adding/Removing function cause it is realy simple and it can be very specific for every application(deleting by ajax...) so I think it woul be better if it is on yourself. 

PS: Be carefull while styleing your lists this way - ul li ul li {...} cause current li is the first level of beseElement.
