### ISSUE TITLE
GNU License is too restrictive

### ISSUE THREAD

**Issue by nevf** [camohub/jquery-sortable-lists#12]
From memory the GNU License prevents use in applications without open source release of all code in that application. Unfortunately this will prevent your code being used by many people. Please consider changing to a more permissive license.

**Comment by camohub** [comment]
Licences are not my domain. Can you tell me which will be bets for this. I don't want to prevent people use it. What about MIT?

**Comment by nevf** [comment]
@camohub Yes MIT is good, thanks.

**Comment by camohub** [comment]
Done.
