### ISSUE TITLE
Separate Drag Handle

### ISSUE THREAD

**Issue by nevf** [camohub/jquery-sortable-lists#13]
It looks like you can only commence a drag on \<li\> elements. Is it possible to specify a separate element _(li child)_ that can be used as the drag element or handle?

**Comment by camohub** [comment]
Hi,
you can create "only draggable" area in LI using child element with ignoreClass which will prevent onDragStart event. Remain area around that child will be draggable. Look at the ignoreClass in documentation. 
Hope you understand me.

**Comment by nevf** [comment]
@camohub Thanks for the prompt response. I've been trying ```ignoreClass``` however this quickly becomes messy to obtain the behaviour I want. 

For example:
````<span><span>[+]</span><em class="clickable">Hello</em><span class="clickable">Item b2 - clickable text</span></span>````
means I need to add the ```ignoreClass``` to every child element.

dragula https://github.com/bevacqua/dragula has a ```moves``` options callback which is passed the element about to be dragged and returns true if the drag can start, else false. This makes it easy to implement a drag handle etc. This should be easy to add to ```this.on( 'mousedown'``` function. 

What do you think?

**Comment by camohub** [comment]
I am not sure if this is necessary for this type of plugins. This is the first requirement to this function. 
I have not enough time to implement it yet. 
:) If you can and if you think it should be easy you can do a fork. But I am really not sure if this is necessary and if I'll merge it.

Have a nice day.
