### ISSUE TITLE
<li> children and descendants

### ISSUE THREAD

**Issue by nevf** [camohub/jquery-sortable-lists#14]
The docs say:
>Note that li items can contains only one or max two direct children. 

Can you explain why there is this limitation and how we can work around it. I want to use "jsl" in a wysiwyg html editor to let the use rearrange lists. The content within an <li> can be anything. For example:

````
<li>eric idle&nbsp;<i>was a&nbsp;<b>very</b> nice</i> <a rel="nofollow" target="_blank" href="http://www.person.com">person</a>.</li>
````

Do I have to wrap all content within the \<li\> in a \<div\> or \<span\> which might be difficult to accomplish.

**Comment by camohub** [comment]
It is not so simple. The only way is to write a plugin for that wysiwyg which will create required type of list or rewrite this. I can't help you with this.

**Comment by nevf** [comment]
@camohub Thanks for your reply. Is this requirement for max two children a limit to what can be in the "Currently dragged element" or does it also apply to the underlying \<li\> as well. If it is a limit of what can be in the "Currently dragged element" then I can remove the child markup when creating the drag element.

**Comment by camohub** [comment]
If I remember this requirement is necessary to creating nested lists.
