### ISSUE TITLE
complete is called after each click and not only after a drop to another position

### ISSUE THREAD

**Issue by dirkjacobs** [camohub/jquery-sortable-lists#16]
I would like to persist the menu in case the position was changed after a drop.
I implemented this in the 'complete' callback but I see that this callback is also called after just clicking a menu-item and not only after a drop to another position as expected.

**Comment by camohub** [comment]
Yes it is called every time after the drop. Not only if the position was changed. It seems you will do some redundant persists.

**Comment by Pejic88** [comment]
I have an issue also with this. I want to trigger an ajax call after complete drop not after every click on element which is considered as complete move.

**Comment by camohub** [comment]
Try to save position or parent el. or both by onDragStart callback and check it in complete callback. If it is the same position don't trigger ajax.

**Comment by camohub** [comment]
May be it could be the implemented in plugin as onChange callback.

**Comment by Pejic88** [comment]
Yes, maybe you should change the wording. Rename "Complete"  to "Change" and implement new callback "Update" which will be called after user drops element.

**Comment by camohub** [comment]
Why update if nothing was updated?

**Comment by Pejic88** [comment]
Hm... Yes, it makes sense.

Then leave Complete callback and implement Change callback as you wrote above. :+1:

**Comment by camohub** [comment]
Ok onChange callback was implemented.

**Comment by Pejic88** [comment]
Oh, great, it was quick :smile: 
I test it, it's working
