### ISSUE TITLE
"insert on hover" feature

### ISSUE THREAD

**Issue by erykpiast** [camohub/jquery-sortable-lists#17]
As far as I see, inserting nested element is based on `insertZone` threshold currently. User has to move the mouse some distance from the left edge of the element and if this distance is above the threshold, dragged element is inserted as a child to hovered one.

We could add optional feature that allows to change (or extend) this behavior (from UX perspective): when user hovers the element, dragged one becomes its child. In my case all attempts to simulate this by changing `insertZone` made widget unusable (ex. when value is 0 there was no way to reorder elements).

Technically we may reuse the mechanism and create something like 'vertical insert zone'. If the mouse is close enough to the vertical center of hovered element, dragged one will become its child when dropped, otherwise elements are reordered.

See attached image for explanation.
![sortable_design](https://cloud.githubusercontent.com/assets/1434406/10965205/b2fffd5c-83ab-11e5-9c8d-506d82ca42f0.png)

What do you think?

**Comment by camohub** [comment]
I think I understand you. It is quite interesting.

**Comment by camohub** [comment]
Hi, I have it. You can try it in dev3 branch. Lok at that please and tell me it there is no bug. It looks pretty good.

**Comment by erykpiast** [comment]
It's perfect, thanks!

**Comment by camohub** [comment]
No I am going to release it as version 2.0.0. I want to keep the code as clean as possible. So I don't want to add new variables and conditions. I think this is more intuitive behavior as that before and is not necessary to support it.

**Comment by camohub** [comment]
But I need to check if it works right. Mainly if export functions does not produce wrong results e.g empty hintWrappers and so.

**Comment by camohub** [comment]
Oo there is a problem with opening closed lists. It shouldn't be opened every time.

**Comment by camohub** [comment]
Ok done, but I am not sure. List jumping up and down too quickly while dragging.

**Comment by camohub** [comment]
Now this behavior is optional. You can allow it in options via insertZonePlus param. Default is false.

**Comment by erykpiast** [comment]
:+1:
