### ISSUE TITLE
Add row

### ISSUE THREAD

**Issue by smartmeter** [camohub/jquery-sortable-lists#18]
Does this support adding row, with 2 columns like a simple table row [text box , drop down list]

**Comment by camohub** [comment]
No, plugin does not know what, where, why to add. It is not its task.
Thats one line of code like 
```
a.on('click', function () { this.closest('li').append( myRow ); } );
```

**Comment by smartmeter** [comment]
:+1: thanks for sharing the snippet.

I agree its not the task, for newcomers, just asking how to extend and include that, for e.g. I was try to get this same thing working, http://bit.ly/1WbjVGz

**Comment by camohub** [comment]
Main problem is that you have no problem with plugin. I don't know where are the borders of this plugin in join with your implementation. That example in link should work.

**Comment by smartmeter** [comment]
ok thanks, I tried it but was not able to get the row with a `datepicker` or `dropdownlist`  to work. It would be very practical if it could, as an option if I get all columns back posted to the server via AJAX

I agree with you on where the borders lie... I was saying this would be a nice differentiate it from the Jquery UI plugin and others out there. I see a lot of potential

**Comment by camohub** [comment]
Can you explain what is the problem with drop down list? Do you mean select input?
