### ISSUE TITLE
Can the item/content it hold any HTML content

### ISSUE THREAD

**Issue by smartmeter** [camohub/jquery-sortable-lists#19]
Am I allowed to put other HTML content in there? or is it only text.

For e.g. Drop down list, date picker, image

**Comment by camohub** [comment]
Yes you can but I think date picker wont work properly. Problem will be with click event. Try it and give me a feetback.

**Comment by smartmeter** [comment]
BTW :+1: this is the best one out there yet, for the following reasons. Serialize the full tree to list with 3 formats.

To clarify the question, can the list items hold/nest as content holders `<Div></Div>` I am trying to add some content like someone was also looking -  http://bit.ly/1NiJz7A 

My scenario is very similar to the above link

     <div class="sorting">
    <div>
        <ul class="Holder">
            <li>
                <div>MenuI_tem</div>
                <ul>
                    <li>
                        <div>MenuItem.1</div>
                        <ul>
                            <li>
                                <div>Menuem.1.1</div>
                            </li>
                            <li>
                                <div>MenuItem.1.2</div>
                            </li>
                            <li>
                                <div>MenuItem.1.3</div>
                                <ul>
                                    <li>
                                        <div>MenuItem.1.3.1</div>
                                        <ul>
                                            <li>
                                                <div>MenuItem.1.3.1.1</div>
                                            </li>
                                            <li>
                                                <div>MenuItem.1.3.1.2</div>
                                            </li>
                                        </ul>
                                    </li>
                                    <li>
                                        <div>MenuItem.1.3.1</div>
                                    </li>
                                </ul>
                            </li>

**Comment by camohub** [comment]
Do you mean how to do this: http://api.jquery.com/jquery.ajax/ ?

**Comment by smartmeter** [comment]
not quite, but I was asking to nest/tie in the HTML content by default as an option. For e.g. specify DIV, and the plug in is aware of the content.
