### ISSUE TITLE
Add/Remove events

### ISSUE THREAD

**Issue by Pejic88** [camohub/jquery-sortable-lists#20]
Is there a possibility to insert new elements or remove existing elements from the list?
Should I do some reinitialization after add/remove element ? Can you explain me that flow?

**Comment by camohub** [comment]
No it is not implemented. 
Only thing you have to do is to ensure right structure of html tree. 
```
var newItem = $('<li><div>new item</div><li/>');
a.on('click', function() { a.on('click', function() { this.closest('li').before( newItem ); } );
```
If you want to insert new item into li element you have to ensure that newItem item is wrapped with ul/ol element.
```
var newItem = $('<li><div>new item</div><li/>');
a.on('click', function() { 
    var li = this.closest('li');
    if( li.find('ul').first().length ) li.find('ul').first().prepend( newItem );
    else li.append( newItem.wrap('<ul></ul>'); );
});
```
I didn't check that code above. It is only idea.

**Comment by Pejic88** [comment]
Yeah, I got that.

I'll try something in that way.
