### ISSUE TITLE
Question: can it be used with a jQuery Draggable?

### ISSUE THREAD

**Issue by mirko77** [camohub/jquery-sortable-lists#23]
I really like this implementation, I would like to know if it is possible to drag and drop items from a Draggable widget

**Comment by camohub** [comment]
Drag another elements which are inside the li element? Can you explain it little more?

**Comment by mirko77** [comment]
Let's say I have a list of items on a sidebar, and I want to drag the one I choose into the sortable.

Like the connected lists of jQuery UI here https://jqueryui.com/sortable/#connect-lists

I need the sortable only on the right list though

**Comment by camohub** [comment]
I dont know. Make two sortable lists and try to drag items between them. I realy dont know what happens.
