### ISSUE TITLE
Does not work on iPad

### ISSUE THREAD

**Issue by 1of3** [camohub/jquery-sortable-lists#24]
I'm using an iPad Air 2 and implemented the changes you mentioned in issue #2.
The dragging seems to work ok but the issue I'm seeing is it does not register when I release the item.

I can use the zoom functionality on the iPad which then sometimes releases the item.

**Comment by camohub** [comment]
Which browser is it? I tried to implement it, but there is a bug in Chrome which does not trigger neccessary event( touchEnd ) after touchMove. I have prepared it in dev branch. Look at it if you want.
