### ISSUE TITLE
complete : Uncaught ReferenceError: cE1 is not defined

### ISSUE THREAD

**Issue by relaxou** [camohub/jquery-sortable-lists#25]
complete: function( cEl )
        { 
            console.log( 'complete' );
        },

hello,

I'd like to add a database update when a move is completed. But i got this error "Uncaught ReferenceError: cE1 is not defined" when i try to use cE1.  I can see the content of cE1 with chrome debugger but only on the line "complete: function(cE1)". 

Could you help me please ?

Thanks

**Comment by relaxou** [comment]
I just see it's a "l" not "1" ^^

**Comment by camohub** [comment]
Hey man, you should use onChange if you want to update db.

**Comment by relaxou** [comment]
Oh yes. Thanks a lot
