### ISSUE TITLE
Problem with isAllowed callback

### ISSUE THREAD

**Issue by Pejic88** [camohub/jquery-sortable-lists#26]
I have a problem with isAllowed callback, the plugin doesn't give me the proper target element.
![screenshot_1](https://cloud.githubusercontent.com/assets/2436669/12592168/8c4612d6-c46b-11e5-9054-a360116fce35.png)

**Comment by camohub** [comment]
Yes there is a bug. Can you use hint.parents('li').first() instead?

**Comment by Pejic88** [comment]
Ok, I'll try in that way and I'll let you know if it's working for me. I think you shouldn't remove target param, it can be useful to have it as a prepared jQuery object, not to target it always via hint.parents...

**Comment by Pejic88** [comment]
@camohub I tried the solution you wrote above and it's working. Tnx! :+1:

**Comment by camohub** [comment]
Fixed in v1.1.1
