### ISSUE TITLE
Dropdown list cannot be selected

### ISSUE THREAD

**Issue by caizhenxing** [camohub/jquery-sortable-lists#33]
@camohub if the list contains dropdown list, we cannot select the option from the dropdown list,

below is the example:
https://jsfiddle.net/haiquan180/szmjhjok/

input also doesn't work.

could you help me? i really need dropdown, input to work.

**Comment by camohub** [comment]
You have at least two mistakes in the code. Look at documentation for the structure of items(there is one div not two on the first level) and also for ignoreClass option.
