### ISSUE TITLE
is it possible to delete or edit a node?

### ISSUE THREAD

**Issue by mahsa92** [camohub/jquery-sortable-lists#4]

**Comment by camohub** [comment]
Hi, it is not implemented. Can you explain that edit? What do you want to achieve?

**Comment by mahsa92** [comment]
for example rename the "Item a" to "Item 1"

**Comment by ywg** [comment]
If you manually append the correct list structure (ul/li) inside your tree node, it will work right ahead.

**Comment by camohub** [comment]
I think this is not a function of this plugin. But may be I dont understant. Need some example...
