### ISSUE TITLE
support for jquery 3.2.1

### ISSUE THREAD

**Issue by shorif2000** [camohub/jquery-sortable-lists#40]
i am trying to install this via composer bower-asset library.

when will it support jquery 3.2.1

`
~/composer require bower-asset/jquery-sortable-lists
Using version ^1.3 for bower-asset/jquery-sortable-lists
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for bower-asset/jquery-sortable-lists ^1.3 -> satisfiable by bower-asset/jquery-sortable-lists[v1.3.0].
    - Conclusion: remove bower-asset/jquery 3.2.1
    - Conclusion: don't install bower-asset/jquery 3.2.1
    - bower-asset/jquery-sortable-lists v1.3.0 requires bower-asset/jquery >=1,<3.0.0 -> satisfiable by bower-asset/jquery[2.2.4, 2.2.3, 2.2.2, 2.2.1, 2.2.0, 2.1.4, 2.1.3, 2.1.2, 2.1.1, 2.1.0, 2.0.3, 2.0.2, 2.0.1, 2.0.0, 1.12.4, 1.12.3, 1.12.2, 1.12.1-patch1, 1.12.1, 1.12.0, 1.11.3, 1.11.2, 1.11.1, 1.11.0, 1.10.2, 1.10.1, 1.10.0, 1.9.1, 1.9.0, 1.8.3-patch1, 1.8.3, 1.8.2, 1.8.1, 1.8.0, 1.7.2, 1.7.1, 1.7.0, 1.6.4, 1.6.3, 1.6.2, 1.6.1, 1.6.0, 1.5.2, 1.5.1, 1.5.0, 1.4.4, 1.4.3, 1.4.2, 1.4.1, 1.4.0, 1.3.2, 1.3.1, 1.3.0, 1.2.6, 1.2.5, 1.2.4, 1.2.3, 1.2.2, 1.2.1, 1.2, 1.1.4, 1.1.3.1, 1.1.3, 1.1.2, 1.1.1, 1.1, 1.0.4, 1.0.3, 1.0.2, 1.0.1, 1.0].
    - Can only install one of: bower-asset/jquery[2.2.4, 3.2.1].
    - Can only install one of: bower-asset/jquery[2.2.3, 3.2.1].
    - Can only install one of: bower-asset/jquery[2.2.2, 3.2.1].
    - Can only install one of: bower-asset/jquery[2.2.1, 3.2.1].
    - Can only install one of: bower-asset/jquery[2.2.0, 3.2.1].
    - Can only install one of: bower-asset/jquery[2.1.4, 3.2.1].
    - Can only install one of: bower-asset/jquery[2.1.3, 3.2.1].
    - Can only install one of: bower-asset/jquery[2.1.2, 3.2.1].
    - Can only install one of: bower-asset/jquery[2.1.1, 3.2.1].
    - Can only install one of: bower-asset/jquery[2.1.0, 3.2.1].
    - Can only install one of: bower-asset/jquery[2.0.3, 3.2.1].
    - Can only install one of: bower-asset/jquery[2.0.2, 3.2.1].
    - Can only install one of: bower-asset/jquery[2.0.1, 3.2.1].
    - Can only install one of: bower-asset/jquery[2.0.0, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.12.4, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.12.3, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.12.2, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.12.1-patch1, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.12.1, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.12.0, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.11.3, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.11.2, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.11.1, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.11.0, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.10.2, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.10.1, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.10.0, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.9.1, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.9.0, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.8.3-patch1, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.8.3, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.8.2, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.8.1, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.8.0, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.7.2, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.7.1, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.7.0, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.6.4, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.6.3, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.6.2, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.6.1, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.6.0, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.5.2, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.5.1, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.5.0, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.4.4, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.4.3, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.4.2, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.4.1, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.4.0, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.3.2, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.3.1, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.3.0, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.2.6, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.2.5, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.2.4, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.2.3, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.2.2, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.2.1, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.2, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.1.4, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.1.3.1, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.1.3, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.1.2, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.1.1, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.1, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.0.4, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.0.3, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.0.2, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.0.1, 3.2.1].
    - Can only install one of: bower-asset/jquery[1.0, 3.2.1].
    - Installation request for bower-asset/jquery (locked at 3.2.1) -> satisfiable by bower-asset/jquery[3.2.1].

Installation failed, reverting ./composer.json to its original content.

`

**Comment by camohub** [comment]
If you can test it with JQ 3,0,0 I can update the restriction.

**Comment by camohub** [comment]
FIXED. Test it if you can please.
