### ISSUE TITLE
Moving a child to the the outermost level not possible

### ISSUE THREAD

**Issue by dgonza12** [camohub/jquery-sortable-lists#43]
So I'm facing a problem where if an item is child I can't move to the outermost level. For example if the list consist of one item with a child. I'm not able to make that child a sibling of it's parent. Any idea on how I can make this possible?

**Comment by camohub** [comment]
I understand what you want. It is really not possible.

**Comment by dgonza12** [comment]
there was some css causing me the problem. Now I am able to move items out of their parents.

**Comment by dgonza12** [comment]
I had some css on the list that was causing some errors.

**Comment by camohub** [comment]
I dont understand. Top level is li element not new list.
