### ISSUE TITLE
Moving items that don't allow children

### ISSUE THREAD

**Issue by dgonza12** [camohub/jquery-sortable-lists#45]
I have an item that I don't want other items to be put inside of it. I am preventing this using the isAllowed in the options. The problem is that make it difficult to move items around because the library thinks that I'm trying to move the items inside each other but I'm really trying to change their postions. i.e:

+Parent1
+--Child1
+--Child2
+--Child3
+Parent2
+--Child1
+--Child2

Moving the children is a bit difficult because it thinks I want to put a child and in a child

**Comment by camohub** [comment]
In documentation example is the same problem? 
I dont fully understand the problem. 
I need to see the code of isAllowed callback
