### ISSUE TITLE
Add a new nested list item

### ISSUE THREAD

**Issue by VRDaProgrammers** [camohub/jquery-sortable-lists#47]
Hey there! Thanks for this awesome library. I am using it to implement a system where upon clicking on a button,  a new list item is added to the main ul. Now, the item does get appended but it doesn't receive the icons for the openers that i set in the options. I can see the list item and it's always opened without the '+' or '-' signs so i can't open or close that particular list item. Can you let me know how that would be done as the only way i found is to re-create the Sortable List using $('element').sortableLists({ options }) but that appends the '+' and '-' icons to each and every list item multiple times

**Comment by camohub** [comment]
Hi, if you need to create new items you has to create the same html structure as the plugin creates manually. Also with opener if item contains nested items.

**Comment by VRDaProgrammers** [comment]
Yes thats working fine. The problem is that the ul elements inside of li are generated dynamically whenever an item is dragged and dropped inside of an li. I want the ul to always be there so that the moment i want something inside of a list, i can just append it. The problem is that even if i do that, it gets replaced with the ul that's generated dynamically

**Comment by camohub** [comment]
If u create ul>li whih the shape it is rewritten? I dont think so. Plugin removes empty uls inside the list at some points. Cause empty uls have no sense in mz opinion. But if the ul is not empty it should not be deleted.

**Comment by VRDaProgrammers** [comment]
That's where the problem is :( It really doesn't make any sense to have empty uls but in my case, it makes sense as layers can be empty. Well, i guess i'm gonna have to change your code a bit as there's no other way.
