### ISSUE TITLE
ignoreClass attribute doesn't work

### ISSUE THREAD

**Issue by piotrrussw** [camohub/jquery-sortable-lists#49]
Hi, 
I have a problem with the ignoreClass property, I tried it as in an example and append it to my checkboxes which are rendered dynamically based on user interaction (so maybe it's the case) and so then inputs with class 'clickable' are still draggable.

**Comment by camohub** [comment]
Show me the code. IgnoreClass is checked at the moment when you do mousedown. It should no matter if element was generated dynamically.
