### ISSUE TITLE
Is there a way to specify which item is currently open and have it open automatically?

### ISSUE THREAD

**Issue by manu144x** [camohub/jquery-sortable-lists#5]
I really like the way it works as a browser and would like to use it that way.

Also is there a parameter which element of the tree is open and to open it there?

Thank you

**Comment by manu144x** [comment]
Ok, I just used the clickable class feature, and works perfectly.

Now, is there a way to tell it which item is currently open? Or I have to do a manual recursive search and open them all up?

**Comment by camohub** [comment]
If you want to show some nested lists you have to add "sortableListsOpen" class to the parent li element of nested list. You can find it in docu in Open/close function section.

**Comment by manu144x** [comment]
I got it, it works very well.

Now there's another interesting thing, is there a way to limit the number of levels, or I have to use the isAllowed function?

**Comment by camohub** [comment]
You must use isAllowed function. Plugin does not check the levels.
