### ISSUE TITLE
jQuerySortableLists opener as background image is deprecated

### ISSUE THREAD

**Issue by simonsalamon** [camohub/jquery-sortable-lists#50]
jQuerySortableLists opener as background image is deprecated. In version 2.0.0 it will be removed. Use html instead please.

i try this plugin in my project but i see this error 
any don't know how can i fix this error

**Comment by camohub** [comment]
There are three ways how to set up opener icon. background image one of them. It is only deprecated warning, but it still  works. You can use html (e.g. favicon) or css class instead. It is described in documentation how to do it.
