### ISSUE TITLE
No html file in zip package

### ISSUE THREAD

**Issue by GoodJob** [camohub/jquery-sortable-lists#51]
It looks like a valuable sortable package, but I struggle to make it work on my pc. There will be huge value of adding index.html working example in the package. It will let save 10mins for each person who downloads this package. Thanks!!!

**Comment by camohub** [comment]
Thank you. The documentation is html with working example. If you show the source html there it is.

**Comment by GoodJob** [comment]
doesn't work

**Comment by camohub** [comment]
What does not work? How can I know what does not work?
