### ISSUE TITLE
How get this in offline?

### ISSUE THREAD

**Issue by rajeshmorla** [camohub/jquery-sortable-lists#6]
I have downloaded zip file, i am not getting how to configure it online. kindly help in this. I need this feature.

**Comment by camohub** [comment]
Do you want an ofline documentation? Actualy it is not in zip ball.
If you can pull the Git repository you will see it in gh-pages or in dev branch.

**Comment by camohub** [comment]
I am not sure if I understand you. Can you explain it better?

**Comment by rajeshmorla** [comment]
Sure, I want this
