### ISSUE TITLE
MaxLevels not working

### ISSUE THREAD

**Issue by lulubytt** [camohub/jquery-sortable-lists#64]
Hello @camohub!  Thanks for a great plugin, this has saved me hours of dev work.  :)

One issue though: the **maxLevels** options is not working.  When I set it to a number, it stops nesting altogether.   If I remove the maxLevels option (it defaults to false), it starts nesting again.

Please advise. Thanks!

**Comment by camohub** [comment]
Hi, I fixed it. Try the newest version 2.4 and use minified version please. 

Added item has to have `data-upper-level="0"` and `data-inside-levels="0"` attributes. 

Let me know how it turned out.

**Comment by lulubytt** [comment]
Worked like a charm! Thanks so much :)
