### ISSUE TITLE
JSON.stringify Error

### ISSUE THREAD

**Issue by tablebubble** [camohub/jquery-sortable-lists#66]
I'm sending sortableListsToArray() wrapped in JSON.stringify() in a form post, the PHP var_dump shows the structure but when I try to iterate the content using json_decode, I get NULL and using json_last_error_msg() I get syntax error. 

please help.

**Comment by camohub** [comment]
Can you show the var_dump and the code here?

**Comment by tablebubble** [comment]
My sincere apologies, I really appreciate your prompt response but I figure a away around the error.
using preg_replace fixed the error from the POST.

if(isset($_POST['submit'])){
        $id = $_GET['id']; // id is survey ID
        // global $wpdb;
        var_dump($_POST); 
// result: array(3) { ["submitquestion"]=> string(4) "true" ["q"]=> string(31) "[{\"id\":\"9635\",\"order\":0}]" ["submit"]=> string(13) "Save Question" } 
        $ql = $_POST['q'];
        var_dump($ql); // Result: string(31) "[{\"id\":\"9635\",\"order\":0}]"
        // $new_q = str_repeat('\\', '', $ql);
        $new_q = preg_replace('/\\\\/', '', $ql);  // this is my fix.
        echo $new_q;
        $qjson = json_decode($new_q, true);
        var_dump($qjson); // Result: NULL 
        echo json_last_error_msg(); // Result: Syntax error
        wp_die();
}
