### ISSUE TITLE
'sortableListsPlaceholder' as id

### ISSUE THREAD

**Issue by fjavier-moreno** [camohub/jquery-sortable-lists#8]
Hi!

Plugin is awsome, I have integrated successfully with no many issues but I have last one that still give me a headache.

I have defined this callback on drop completion:
```
complete: function(currEl)
            {
                var $tree = $sortable.sortableListsToArray();
                $.ajax({
                    url: '{{ path('admin_category_sort_component') }}',
                    type: 'POST',
                    data: { data : $tree},
                    success: function(data) {
                        //console.debug(data);
                    }
                });
            }
```

But sortableListsToArray function gave me an element with 'sortableListsPlaceholder':

```
...
    [order] => 0
 )
[2] => Array
(
    [id] => sortableListsPlaceholder
    [parentId] => 92
    [order] => 0
)
...
```

Seems sortableListsToArray is not waiting to id restore after drop completion.

I need export tree data on drop finish in order to save hierarchy automatically.

I'm making anything wrong maybe?

Thanks in advance.

**Comment by camohub** [comment]
I am going to check it.

**Comment by camohub** [comment]
There was a bug if user calls toArray from complete callback. It should be fixed. 
If you want it immediately use gothub repository. Bower/NPM is not available yet.

**Comment by fjavier-moreno** [comment]
Thanks a lot!!

**Comment by camohub** [comment]
Bower and NPM are available.

Have a nice day.
